'use client'

import { ChangeEvent, useEffect, useRef, useState } from 'react'
import { AlertCircle, Camera, Check, ChevronRight, FileImage, Loader2, RotateCcw, ScanLine, Sparkles, Upload, X } from 'lucide-react'

type Phase = 'idle' | 'processing' | 'success' | 'error'
type Provider = 'gemini' | 'openai'
type FieldValue = { value: string | null; status: 'confirmed' | 'unknown' }
type IdentificationState = { round: number; purchase_ready: boolean; purchase_spec: string; fields: Record<string, FieldValue>; missing_for_purchase: string[]; next_action: { type: string; instruction: string } | null; summary: string; diagnostic?: unknown }
type CvSignal = { period_px: number | null; score: number | null; roi: string; method: string }
type PreparedImage = { base: string; variants: string[]; cv: CvSignal }

const fieldLabels: Record<string, string> = { part_type: '零件類型', thread_system: '制式／螺紋系統', nominal_size: '公稱尺寸', length: '長度', pitch_tpi: '牙距／TPI', head_type: '頭型', drive: '驅動方式', material_finish: '材質／表面處理' }

export default function Page() {
  const [imageUrl,setImageUrl]=useState(''); const [imageData,setImageData]=useState(''); const [imageVariants,setImageVariants]=useState<string[]>([]); const [cvSignal,setCvSignal]=useState<CvSignal|null>(null); const [originalImageData,setOriginalImageData]=useState('')
  const [phase,setPhase]=useState<Phase>('idle'); const [provider,setProvider]=useState<Provider|null>(null); const [state,setState]=useState<IdentificationState|null>(null); const [error,setError]=useState(''); const [additionReady,setAdditionReady]=useState(false)
  const inputRef=useRef<HTMLInputElement>(null)
  useEffect(()=>()=>{if(imageUrl)URL.revokeObjectURL(imageUrl)},[imageUrl])

  async function handleFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setError('');setPhase('idle');const previewUrl=URL.createObjectURL(file);setImageUrl(p=>{if(p)URL.revokeObjectURL(p);return previewUrl});const prepared=await prepareImage(file);setImageData(prepared.base);setImageVariants(prepared.variants);setCvSignal(prepared.cv);if(!state){setOriginalImageData(prepared.base);setAdditionReady(false)}else setAdditionReady(true)}
  function resetAll(){setImageUrl('');setImageData('');setImageVariants([]);setCvSignal(null);setOriginalImageData('');setState(null);setError('');setPhase('idle');setProvider(null);setAdditionReady(false);if(inputRef.current)inputRef.current.value=''}
  async function analyze(selectedProvider:Provider){if(!imageData)return;setProvider(selectedProvider);setPhase('processing');setError('');try{const response=await fetch('/api/benchmark-identify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:imageData,image_variants:imageVariants,cv_signal:cvSignal,original_image:state?originalImageData:'',provider:selectedProvider,previous_state:state})});const data=await response.json();if(!response.ok)throw new Error(data.error||'辨識服務暫時無法使用');setState(data.state);setPhase('success');setAdditionReady(false)}catch(caught){setError(caught instanceof Error?caught.message:'發生未知錯誤');setPhase('error')}}
  const continuing=Boolean(state&&!state.purchase_ready&&state.next_action);const confirmedFields=state?Object.entries(state.fields).filter(([,f])=>f.status==='confirmed'&&f.value):[];const unknownFields=state?Object.entries(state.fields).filter(([,f])=>f.status==='unknown'):[]

  return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto w-full max-w-5xl px-5 pb-12 sm:px-8"><header className="flex items-center justify-between border-b border-border py-5"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-lg bg-primary text-primary-foreground"><ScanLine size={19}/></div><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.22em] text-muted-foreground">HCSI / CV PERIOD TEST</p><p className="text-sm font-semibold">漸進式五金辨識</p></div></div>{state&&<span className="text-xs text-muted-foreground">第 {state.round} / 3 輪</span>}</header>
  <section className="py-9"><div className="mb-7 max-w-2xl"><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">先讓程式找重複週期，<span className="text-accent">再交給 AI 判斷。</span></h1><p className="mt-3 text-sm leading-6 text-muted-foreground">這版在瀏覽器先做快速 1D autocorrelation，只提供像素週期，不自行決定螺紋規格。</p></div><div className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="overflow-hidden rounded-xl border border-border bg-card">
  {!imageUrl?<button type="button" onClick={()=>inputRef.current?.click()} className="flex min-h-[320px] w-full flex-col items-center justify-center gap-4 p-8 text-center hover:bg-muted/50"><span className="grid size-14 place-items-center rounded-xl border border-border bg-muted"><Camera size={25}/></span><strong>{continuing?'上傳追加證據照片':'拍照或上傳零件'}</strong><span className="text-sm text-muted-foreground">建議使用螺紋放大、軸線接近水平的照片</span><span className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm text-primary-foreground"><Upload size={15}/>選擇影像</span></button>:<div className="relative"><img src={imageUrl} alt="辨識影像" className="max-h-[420px] min-h-[300px] w-full bg-muted/30 object-contain p-3"/><span className="absolute left-4 top-4 rounded-md bg-primary/90 px-2.5 py-1.5 text-[11px] text-primary-foreground"><FileImage className="mr-1 inline" size={13}/>CV PERIOD TEST</span><button type="button" onClick={()=>inputRef.current?.click()} className="absolute right-4 top-4 grid size-9 place-items-center rounded-md bg-primary/90 text-primary-foreground"><RotateCcw size={16}/></button></div>}
  <input ref={inputRef} className="sr-only" type="file" accept="image/*" onChange={handleFile}/>{cvSignal&&<div className="border-t border-border bg-muted/20 px-4 py-3 text-xs"><strong>LOCAL CV</strong><span className="ml-3 text-muted-foreground">period: {cvSignal.period_px??'—'} px · score: {cvSignal.score??'—'} · {cvSignal.roi}</span></div>}{additionReady&&<div className="border-t border-border bg-accent/5 px-4 py-3 text-sm"><Check className="mr-2 inline text-accent" size={16}/>追加照片已上傳，請繼續分析。</div>}
  {imageUrl&&<div className="grid gap-2 border-t border-border p-4 sm:grid-cols-2"><button onClick={()=>analyze('gemini')} disabled={phase==='processing'} className="flex items-center justify-center gap-2 rounded-md bg-accent px-4 py-3 text-sm font-semibold disabled:opacity-60">{phase==='processing'&&provider==='gemini'?<Loader2 className="animate-spin" size={16}/>:<Sparkles size={16}/>}Gemini</button><button onClick={()=>analyze('openai')} disabled={phase==='processing'} className="flex items-center justify-center gap-2 rounded-md border border-border px-4 py-3 text-sm font-semibold disabled:opacity-60">{phase==='processing'&&provider==='openai'?<Loader2 className="animate-spin" size={16}/>:<Sparkles size={16}/>}OpenAI</button></div>}</div>
  <div aria-live="polite">{!state&&phase!=='error'&&<div className="flex min-h-[320px] items-center justify-center rounded-xl border border-dashed border-border p-8 text-center text-sm leading-6 text-muted-foreground">上傳後會先在本機計算螺紋候選週期。<br/>這一步不需要 API。</div>}{phase==='processing'&&<div className="mb-4 flex items-center gap-3 rounded-xl border border-border bg-card p-5"><Loader2 className="animate-spin text-accent" size={18}/><div><p className="text-sm font-semibold">正在分析</p><p className="text-xs text-muted-foreground">AI 會收到本機 CV 的週期候選作為額外觀察。</p></div></div>}{state&&<div className="space-y-4"><div className="rounded-xl border border-border bg-card p-5"><p className="text-xs font-semibold text-accent">{state.purchase_ready?'已足以購買':'目前可提供給五金行的資訊'}</p><h2 className="mt-3 text-xl font-semibold">{state.purchase_spec}</h2>{state.summary&&<p className="mt-3 text-sm leading-6 text-muted-foreground">{state.summary}</p>}</div><div className="rounded-xl border border-border bg-card p-5"><h3 className="text-sm font-semibold">已確認</h3><div className="mt-3">{confirmedFields.map(([key,f])=><div key={key} className="flex gap-2 py-1.5 text-sm"><Check size={16} className="text-accent"/><span className="min-w-24 text-muted-foreground">{fieldLabels[key]||key}</span><strong>{f.value}</strong></div>)}</div></div>{state.diagnostic&&<div className="rounded-xl border border-dashed border-border bg-muted/20 p-5"><h3 className="text-sm font-semibold">TEST DIAGNOSTIC</h3><pre className="mt-3 whitespace-pre-wrap break-words text-xs leading-5 text-muted-foreground">{JSON.stringify(state.diagnostic,null,2)}</pre></div>}{!state.purchase_ready&&<div className="rounded-xl border border-border bg-card p-5"><h3 className="text-sm font-semibold">還缺什麼</h3><p className="mt-2 text-sm">{state.missing_for_purchase.length?state.missing_for_purchase.map(x=>fieldLabels[x]||x).join('、'):'沒有明確缺失欄位'}</p>{state.next_action&&<div className="mt-4 rounded-lg bg-muted p-4"><p className="text-sm">{state.next_action.instruction}</p><button onClick={()=>inputRef.current?.click()} className="mt-3 inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm text-primary-foreground">補一張照片<ChevronRight size={15}/></button></div>}{unknownFields.length>0&&<p className="mt-3 text-xs text-muted-foreground">其他欄位保留未知。</p>}</div>}<button onClick={resetAll} className="flex items-center gap-2 text-sm text-muted-foreground"><X size={14}/>開始辨識另一個零件</button></div>}{phase==='error'&&<div className="flex gap-3 rounded-xl border border-destructive/30 bg-card p-5 text-sm"><AlertCircle size={18}/><div><p className="font-semibold">辨識未完成</p><p className="mt-1 text-muted-foreground">{error}</p></div></div>}</div></div></section></div></main>
}

function prepareImage(file:File):Promise<PreparedImage>{return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{const scale=Math.min(1,1600/image.width,1600/image.height);const width=Math.max(1,Math.round(image.width*scale)),height=Math.max(1,Math.round(image.height*scale));const source=document.createElement('canvas');source.width=width;source.height=height;const ctx=source.getContext('2d',{willReadFrequently:true});if(!ctx)return reject(new Error('無法處理影像'));ctx.drawImage(image,0,0,width,height);const base=source.toDataURL('image/jpeg',0.9).split(',')[1];const cv=estimatePeriod(ctx,width,height);URL.revokeObjectURL(image.src);resolve({base,variants:[],cv})};image.onerror=()=>reject(new Error('影像讀取失敗'));image.src=URL.createObjectURL(file)})}

function estimatePeriod(ctx:CanvasRenderingContext2D,width:number,height:number):CvSignal{
  // Minimal benchmark detector: center horizontal band, suitable for the current enlarged side-view thread test.
  const x0=Math.round(width*0.12),x1=Math.round(width*0.88),y0=Math.round(height*0.30),y1=Math.round(height*0.70);const w=x1-x0,h=y1-y0
  if(w<80||h<20)return{period_px:null,score:null,roi:'center 76% × 40%',method:'1D gradient autocorrelation'}
  const data=ctx.getImageData(x0,y0,w,h).data;const signal=new Array<number>(w).fill(0)
  for(let x=1;x<w;x++){let sum=0;for(let y=0;y<h;y+=2){const i=(y*w+x)*4,j=(y*w+x-1)*4;const a=.299*data[i]+.587*data[i+1]+.114*data[i+2],b=.299*data[j]+.587*data[j+1]+.114*data[j+2];sum+=Math.abs(a-b)}signal[x]=sum/Math.ceil(h/2)}
  const mean=signal.reduce((a,b)=>a+b,0)/signal.length;for(let i=0;i<signal.length;i++)signal[i]-=mean
  let bestLag=0,best=-Infinity;const minLag=Math.max(3,Math.round(w/120)),maxLag=Math.min(Math.round(w/8),100)
  for(let lag=minLag;lag<=maxLag;lag++){let num=0,a2=0,b2=0;for(let i=0;i<w-lag;i++){const a=signal[i],b=signal[i+lag];num+=a*b;a2+=a*a;b2+=b*b}const corr=num/Math.sqrt(Math.max(1,a2*b2));if(corr>best){best=corr;bestLag=lag}}
  return{period_px:bestLag||null,score:Number.isFinite(best)?Math.round(best*1000)/1000:null,roi:'center 76% × 40%',method:'1D horizontal-gradient autocorrelation'}
}