import type { NominalCandidate } from './measurement-v2'
import type { CandidateFeatureMatrix } from './candidate-feature-compiler'
import type { CandidateSemanticDiscrimination } from './candidate-semantic-discrimination'
import type { SemanticFeatureId } from './semantic-taxonomy-v1'
export const EVIDENCE_CONVERGENCE_SCHEMA='hcsi.evidence-convergence.v1' as const
export type ConvergenceDecisionState='purchase_ready'|'purchase_ready_with_confirmation'|'targeted_followup_required'|'unresolved'|'contradictory_evidence'
export interface RequestedEvidence{feature_id:SemanticFeatureId|'physical.D'|'physical.P'|'physical.length';acquisition:'drive_face_view'|'head_profile_view'|'thread_pitch_measurement'|'diameter_measurement'|'length_measurement_view'|'semantic_feature_view';reason:'remaining_candidates_disagree';affected_candidates:string[];partition_count:number;largest_partition:number}
export interface EvidenceConvergenceResult{schema_version:typeof EVIDENCE_CONVERGENCE_SCHEMA;decision:ConvergenceDecisionState;decision_strength:'unique_formal_candidate'|'materially_equivalent_candidates'|'multi_source_convergence'|'unresolved_material_ambiguity'|'contradiction_present'|'followup_discriminator_available';selected_candidate_id:string|null;candidate_ids_entered:string[];candidate_ids_surviving:string[];eliminated:Array<{candidate_id:string;reason:'deterministic_semantic_contradiction';features:string[]}>;requested_evidence:RequestedEvidence|null;reason_codes:string[];numeric_confidence:null;posterior_probability:null;evidence_history_refs:string[]}
function semKey(m:CandidateFeatureMatrix|null,id:string){const p=m?.profiles.find(x=>x.candidate_id===id);return p?p.feature_constraints.filter(x=>x.support_status==='normative_metadata'&&!['not_specified','unknown'].includes(x.relation)).map(x=>`${x.feature_id}:${x.relation}:${x.expected_value??''}`).sort().join('|'):''}
function materialKey(c:NominalCandidate,m:CandidateFeatureMatrix|null){return JSON.stringify({system:c.standard_system,family:c.family,designation:c.designation,d:c.nominal.diameter_mm,p:c.nominal.pitch_mm,tpi:c.nominal.tpi??null,l:c.nominal.length_mm,lc:c.nominal.length_convention,semantic:semKey(m,c.candidate_id)})}
function contrad(d:CandidateSemanticDiscrimination|null,id:string){return d?.candidates.find(x=>x.candidate_id===id)?.feature_evaluations.filter(x=>x.compatibility_state==='contradicts').map(x=>x.feature_id)??[]}
function parts<T>(cs:NominalCandidate[],f:(c:NominalCandidate)=>T){const m=new Map<string,string[]>();for(const c of cs){const k=JSON.stringify(f(c)),a=m.get(k)??[];a.push(c.candidate_id);m.set(k,a)}return[...m.values()]}
const semAcq=(f:SemanticFeatureId):RequestedEvidence['acquisition']=>f==='drive.form'?'drive_face_view':f==='head.profile'?'head_profile_view':'semantic_feature_view'
function discriminators(cs:NominalCandidate[],m:CandidateFeatureMatrix|null){const out:RequestedEvidence[]=[];const add=(feature_id:RequestedEvidence['feature_id'],acquisition:RequestedEvidence['acquisition'],g:string[][])=>{if(g.length>1)out.push({feature_id,acquisition,reason:'remaining_candidates_disagree',affected_candidates:cs.map(c=>c.candidate_id).sort(),partition_count:g.length,largest_partition:Math.max(...g.map(x=>x.length))})};add('physical.D','diameter_measurement',parts(cs,c=>c.nominal.diameter_mm));add('physical.P','thread_pitch_measurement',parts(cs,c=>c.nominal.pitch_mm));add('physical.length','length_measurement_view',parts(cs,c=>({l:c.nominal.length_mm,lc:c.nominal.length_convention})));if(m)for(const f of m.discriminative_features)add(f,semAcq(f),parts(cs,c=>{const x=m.profiles.find(p=>p.candidate_id===c.candidate_id)?.feature_constraints.find(v=>v.feature_id===f);return x?{r:x.relation,v:x.expected_value,s:x.support_status}:null}));const burden:Record<RequestedEvidence['acquisition'],number>={diameter_measurement:1,thread_pitch_measurement:2,drive_face_view:1,head_profile_view:1,length_measurement_view:2,semantic_feature_view:3};return out.sort((a,b)=>(a.largest_partition-b.largest_partition)||(b.partition_count-a.partition_count)||(burden[a.acquisition]-burden[b.acquisition])||a.feature_id.localeCompare(b.feature_id))}
export function convergeEvidence(input:{formal_candidates:readonly NominalCandidate[];feature_matrix?:CandidateFeatureMatrix|null;semantic_discrimination?:CandidateSemanticDiscrimination|null;evidence_history_refs?:readonly string[]}):EvidenceConvergenceResult{const entered=[...input.formal_candidates],ids=entered.map(c=>c.candidate_id);if(new Set(ids).size!==ids.length)throw new Error('duplicate_formal_candidate_id');const m=input.feature_matrix??null,d=input.semantic_discrimination??null;if(m&&m.candidate_ids.some(id=>!ids.includes(id)))throw new Error('feature_matrix_outside_formal_candidate_universe');if(d&&d.candidate_ids_before.some(id=>!ids.includes(id)))throw new Error('semantic_discrimination_outside_formal_candidate_universe');const e=entered.map(c=>({c,f:contrad(d,c.candidate_id)})).filter(x=>x.f.length),survivors=entered.filter(c=>!e.some(x=>x.c.candidate_id===c.candidate_id));const base={schema_version:EVIDENCE_CONVERGENCE_SCHEMA,candidate_ids_entered:ids,candidate_ids_surviving:survivors.map(c=>c.candidate_id),eliminated:e.map(x=>({candidate_id:x.c.candidate_id,reason:'deterministic_semantic_contradiction' as const,features:x.f})),numeric_confidence:null,posterior_probability:null,evidence_history_refs:[...(input.evidence_history_refs??[])]};if(!entered.length)return{...base,decision:'unresolved',decision_strength:'unresolved_material_ambiguity',selected_candidate_id:null,requested_evidence:null,reason_codes:['no_formal_candidate']};if(!survivors.length)return{...base,decision:'contradictory_evidence',decision_strength:'contradiction_present',selected_candidate_id:null,requested_evidence:null,reason_codes:['semantic_evidence_contradicts_all_formal_candidates']};if(survivors.length===1)return{...base,decision:'purchase_ready',decision_strength:e.length?'multi_source_convergence':'unique_formal_candidate',selected_candidate_id:survivors[0].candidate_id,requested_evidence:null,reason_codes:e.length?['formal_candidate_uniquely_survives_deterministic_compatibility']:['single_formal_candidate']};if(new Set(survivors.map(c=>materialKey(c,m))).size===1){const s=[...survivors].sort((a,b)=>a.candidate_id.localeCompare(b.candidate_id))[0];return{...base,decision:'purchase_ready_with_confirmation',decision_strength:'materially_equivalent_candidates',selected_candidate_id:s.candidate_id,requested_evidence:null,reason_codes:['remaining_candidates_materially_equivalent_for_purchase']}}const next=discriminators(survivors,m)[0]??null;return next?{...base,decision:'targeted_followup_required',decision_strength:'followup_discriminator_available',selected_candidate_id:null,requested_evidence:next,reason_codes:['materially_distinct_candidates_remain']}:{...base,decision:'unresolved',decision_strength:'unresolved_material_ambiguity',selected_candidate_id:null,requested_evidence:null,reason_codes:['materially_distinct_candidates_no_supported_discriminator']}}
export function renderTaiwanFollowup(x:EvidenceConvergenceResult){const a=x.requested_evidence?.acquisition;if(!a)return'';return a==='drive_face_view'?'請補拍螺絲頭正面，讓驅動孔完整入鏡。':a==='head_profile_view'?'請補拍螺絲頭側面輪廓，讓頭部與桿部交界完整入鏡。':a==='thread_pitch_measurement'?'請補拍螺紋側面近照並附同平面尺度，以確認牙距。':a==='diameter_measurement'?'請補拍螺紋外徑與同平面尺度，以確認公稱直徑。':a==='length_measurement_view'?'請補拍完整長度與同平面尺度，讓正確的長度基準可量測。':'請補拍可清楚觀察指定特徵的照片。'}
