import { strict as assert } from 'node:assert'
import { mkdtempSync,writeFileSync,mkdirSync,readFileSync } from 'node:fs'
import { tmpdir } from 'node:os';import { join } from 'node:path';import { execFileSync } from 'node:child_process'
import { PREREGISTERED_PRODUCTION_SEMANTIC_CALIBRATION_POLICY_V1 as policy,PRODUCTION_DRIVE_FORM_REQUIRED_CLASSES,SEMANTIC_CALIBRATION_ELIGIBILITY_POLICY_REGISTRY } from './semantic-calibration-policy-v1'
import { PHASE2G_SENSOR_IDENTITY } from './semantic-calibration-phase2g-observation'
import { PRODUCTION_SEMANTIC_CALIBRATION_DATASETS,ADMITTED_SEMANTIC_CALIBRATION_ARTIFACTS,SEMANTIC_CALIBRATION_REGISTRY } from './semantic-calibration-registry'
import { finalizeCaptureAuthority,assessProductionEnvelopeEvidence,assessVerifiedProductionEnvelopeEvidence,uniqueEligibleSpecimenCount,type ProductionCaptureAuthorityV1,type FrozenObservationBinding } from './semantic-calibration-phase2g1-production-envelope'
import { verifyProductionEnvelopeRepositoryProvenance } from './semantic-calibration-phase2g1-git-provenance'

const sha='a'.repeat(64)
function authority(specimen='future-spec-001',image='future-img-001',split:'calibration'|'validation'='calibration'){return finalizeCaptureAuthority({schema_version:'hcsi.production-envelope-capture-authority.v1',authority_id:'auth-'+image,authority_version:'1.0.0',specimen_id:specimen,image_id:image,feature_id:'drive.form',split,acquired_at:'2026-10-05T01:00:00Z',established_at:'2026-10-05T01:01:00Z',source_scope:'independent_real_image',raw:{sha256:sha,byte_length:1000,width_px:512,height_px:512,format:'JPEG',source_ref:'raw://'+image},capture:{capture_type:'user_uploaded_single_image',crop_type:'full_image',viewpoint:'drive_face_visible',visibility:'visible',occlusion_condition:'none',glare_condition:'none'},policy_binding:{policy_id:policy.policy_id,policy_version:policy.policy_version,policy_content_digest_sha256:policy.policy_content_digest_sha256}})}
function observation(a:ProductionCaptureAuthorityV1,authorityCommit:string,id='obs-1'):FrozenObservationBinding{return {observation_id:id,specimen_id:a.specimen_id,image_id:a.image_id,feature_id:'drive.form',split:a.split,observed_at:'2026-10-05T01:02:00Z',image_sha256:a.raw.sha256,capture_authority_digest_sha256:a.content_digest_sha256,capture_authority_commit_sha:authorityCommit,sensor_identity:{...PHASE2G_SENSOR_IDENTITY},original_observation:true}}
const git=(cwd:string,args:string[])=>execFileSync('git',args,{cwd,encoding:'utf8'}).trim()
const root=mkdtempSync(join(tmpdir(),'hcsi-2g1-'));git(root,['init']);git(root,['config','user.email','test@hcsi.invalid']);git(root,['config','user.name','HCSI deterministic test'])
mkdirSync(join(root,'evidence'))
const good=authority();writeFileSync(join(root,'evidence','authority.json'),JSON.stringify(good,null,2)+'\n');git(root,['add','.']);git(root,['commit','-m','authority before outcome']);const authorityCommit=git(root,['rev-parse','HEAD'])
const obs=observation(good,authorityCommit);writeFileSync(join(root,'evidence','observation.json'),JSON.stringify(obs,null,2)+'\n');git(root,['add','.']);git(root,['commit','-m','observation after authority']);const observationCommit=git(root,['rev-parse','HEAD'])
const proof=verifyProductionEnvelopeRepositoryProvenance({repositoryRoot:root,expectedRepository:'deterministic-test-repository',authority:good,authorityPath:'evidence/authority.json',observation:obs,observationCommitSha:observationCommit,observationPath:'evidence/observation.json'})
assert.equal(assessVerifiedProductionEnvelopeEvidence(good,obs,proof).eligible_to_count_as_calibration_evidence,true)
assert.equal(assessProductionEnvelopeEvidence(good,obs).eligible_to_count_as_calibration_evidence,false)
assert.ok(assessProductionEnvelopeEvidence(good,obs).reason_codes.includes('repository_provenance_unverified'))
const fakeObs=observation(good,'1'.repeat(40));assert.throws(()=>verifyProductionEnvelopeRepositoryProvenance({repositoryRoot:root,expectedRepository:'deterministic-test-repository',authority:good,authorityPath:'evidence/authority.json',observation:fakeObs,observationCommitSha:observationCommit,observationPath:'evidence/observation.json'}),/authority_commit_absent/)
assert.throws(()=>verifyProductionEnvelopeRepositoryProvenance({repositoryRoot:root,expectedRepository:'x',authority:good,authorityPath:'evidence/missing.json',observation:obs,observationCommitSha:observationCommit,observationPath:'evidence/observation.json'}),/authority_artifact_absent/)
const malformed=observation(good,'bad');assert.throws(()=>verifyProductionEnvelopeRepositoryProvenance({repositoryRoot:root,expectedRepository:'x',authority:good,authorityPath:'evidence/authority.json',observation:malformed,observationCommitSha:observationCommit,observationPath:'evidence/observation.json'}),/malformed_authority_commit_ref/)
const changed=JSON.parse(JSON.stringify(good));changed.capture.viewpoint='unknown';assert.throws(()=>verifyProductionEnvelopeRepositoryProvenance({repositoryRoot:root,expectedRepository:'x',authority:changed,authorityPath:'evidence/authority.json',observation:obs,observationCommitSha:observationCommit,observationPath:'evidence/observation.json'}),/authority_artifact_content_mismatch/)
const backdated=JSON.parse(JSON.stringify(good));backdated.established_at='2000-01-01T00:00:00Z';backdated.content_digest_sha256=good.content_digest_sha256;assert.throws(()=>verifyProductionEnvelopeRepositoryProvenance({repositoryRoot:root,expectedRepository:'x',authority:backdated,authorityPath:'evidence/authority.json',observation:obs,observationCommitSha:observationCommit,observationPath:'evidence/observation.json'}),/authority_artifact_content_mismatch/)
const wrongOrderRoot=mkdtempSync(join(tmpdir(),'hcsi-2g1-unrelated-'));git(wrongOrderRoot,['init']);git(wrongOrderRoot,['config','user.email','test@hcsi.invalid']);git(wrongOrderRoot,['config','user.name','HCSI test']);writeFileSync(join(wrongOrderRoot,'x'),'x');git(wrongOrderRoot,['add','.']);git(wrongOrderRoot,['commit','-m','unrelated']);const unrelated=git(wrongOrderRoot,['rev-parse','HEAD'])
assert.throws(()=>verifyProductionEnvelopeRepositoryProvenance({repositoryRoot:root,expectedRepository:'x',authority:good,authorityPath:'evidence/authority.json',observation:obs,observationCommitSha:unrelated,observationPath:'evidence/observation.json'}),/observation_commit_absent/)

const bad=(mut:(x:any)=>void)=>{const x=JSON.parse(JSON.stringify(good));mut(x);return assessProductionEnvelopeEvidence(x,obs)}
for(const [mut,reason] of [[(x:any)=>x.capture.viewpoint='unknown','viewpoint_out_of_policy'],[(x:any)=>x.capture.visibility='unknown','visibility_out_of_policy'],[(x:any)=>x.capture.occlusion_condition='partial','occlusion_out_of_policy'],[(x:any)=>x.capture.glare_condition='present','glare_out_of_policy'],[(x:any)=>x.raw.width_px=255,'width_below_policy_minimum'],[(x:any)=>x.raw.height_px=255,'height_below_policy_minimum'],[(x:any)=>x.capture.capture_type='other','capture_type_out_of_policy'],[(x:any)=>x.capture.crop_type='crop','crop_type_out_of_policy'],[(x:any)=>x.feature_id='head.profile','feature_mismatch'],[(x:any)=>x.policy_binding.policy_content_digest_sha256='0'.repeat(64),'policy_lineage_mismatch']] as Array<[(x:any)=>void,string]>){assert.ok(bad(mut).reason_codes.includes(reason))}
const replacement=observation(good,authorityCommit);replacement.original_observation=false as true;assert.ok(assessVerifiedProductionEnvelopeEvidence(good,replacement,proof).reason_codes.includes('replacement_observation_forbidden'))
const repeated=Array.from({length:29},(_,i)=>({authority:good,observation:observation(good,authorityCommit,'obs-'+i),proof}));assert.equal(uniqueEligibleSpecimenCount(repeated).unique_physical_specimen_count,1)
const cross=[{authority:authority('cross','a','calibration'),observation:null,proof:null},{authority:authority('cross','b','validation'),observation:null,proof:null}];assert.ok(uniqueEligibleSpecimenCount(cross).reason_codes.includes('physical_specimen_crosses_splits'))
const forbidden=JSON.parse(JSON.stringify(good));forbidden.source_scope='development_fixture';assert.ok(assessVerifiedProductionEnvelopeEvidence(forbidden,obs,proof).reason_codes.includes('non_real_source_forbidden'))

const bundle=JSON.parse(readFileSync('data/semantic-calibration/manifests/real-2026-001-intake-bundle.json','utf8')),hi=bundle.corpus_manifest.specimens[0].images[0]
const historical=finalizeCaptureAuthority({schema_version:'hcsi.production-envelope-capture-authority.v1',authority_id:'historical-readonly-projection',authority_version:'1.0.0',specimen_id:'real-2026-001',image_id:'real-2026-001-img-01',feature_id:'drive.form',split:'calibration',acquired_at:bundle.acquisition_ledger.entries[0].acquired_at,established_at:bundle.acquisition_ledger.created_at,source_scope:'independent_real_image',raw:{sha256:hi.sha256,byte_length:49950,width_px:hi.width_px,height_px:hi.height_px,format:'JPEG',source_ref:hi.source_ref},capture:{capture_type:hi.capture_type,crop_type:hi.crop_type,viewpoint:hi.viewpoint,visibility:hi.visibility,occlusion_condition:hi.occlusion_condition,glare_condition:hi.glare_condition},policy_binding:{policy_id:policy.policy_id,policy_version:policy.policy_version,policy_content_digest_sha256:policy.policy_content_digest_sha256}})
const hr=assessProductionEnvelopeEvidence(historical,null);assert.equal(hr.eligible_for_policy_envelope,false);assert.ok(hr.reason_codes.includes('viewpoint_out_of_policy')&&hr.reason_codes.includes('visibility_out_of_policy'))
const persisted=JSON.parse(readFileSync('data/semantic-calibration/observations/real-2026-001-observation.json','utf8')),comparison=JSON.parse(readFileSync('data/semantic-calibration/observations/real-2026-001-gt-comparison.json','utf8'))
assert.equal(persisted.content_digest_sha256,'cf8c2ff1c47d64297a48ee1ba363a350ffaa83091b383c7aee02a86ee73a66d1');assert.equal(persisted.evidence.observations.find((x:any)=>x.feature_id==='drive.form').value,'not_visible');assert.equal(comparison.correct,false)
assert.equal(PRODUCTION_SEMANTIC_CALIBRATION_DATASETS.length,0);assert.equal(ADMITTED_SEMANTIC_CALIBRATION_ARTIFACTS.length,0);assert.equal(SEMANTIC_CALIBRATION_REGISTRY.length,0);assert.equal(SEMANTIC_CALIBRATION_ELIGIBILITY_POLICY_REGISTRY.length,1)
console.log('Phase 2G.1 verifiable pre-outcome provenance regressions A-X + genuine Git positive control passed')
console.log(JSON.stringify({negative_nonexistent_sha:'rejected: authority_commit_absent',positive_real_git_provenance:'eligible',real_physical_specimens:1,real_images:1,semantic_observations:1,production_envelope_eligible_unique_specimens:0,eligible_support:Object.fromEntries(PRODUCTION_DRIVE_FORM_REQUIRED_CLASSES.map(c=>[c,0])),production_state:{datasets:0,artifacts:0,semantic_registry:0,policy_registry:1}},null,2))
